# Generated by Django 3.0.3 on 2020-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbot',
            name='type',
            field=models.CharField(choices=[('mail', 'mail')], default=0, max_length=10, verbose_name='通知类型'),
        ),
    ]
